name: mysqltest
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  smooth_star_rating: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/cover.jpg
    - assets/images/tower.jpg
    - assets/images/omar.jpg
    - assets/images/usercover.jpg

  fonts:
    - family: Spectral
      fonts:
        - asset: assets/fonts/Spectral-Regular.ttf
          weight: 400
        - asset: assets/fonts/Spectral-Medium.ttf
          weight: 500
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 200
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700